name: Test resharper-test-action
on: 
  push:
    branches:
      - "*"
      - "!main"
  workflow_dispatch:
    inputs:
      repositoryName:
        description: 'Repository Name (e.g. GitHubActions.Credentials)'
        required: true
jobs:
  test-action:
    name: Test resharper-action
    runs-on: ubuntu-20.04

    steps:
      - name: Verify Repo Not Empty
        run: |
            VAR = "${{github.event.inputs.repositoryName}}"
            print ("${VAR}")
            if [ -z "${VAR}" ]; then
                echo "VAR is unset or set to the empty string"
                exit 1
            fi
            if [ -z "${VAR+set}" ]; then
                echo "VAR is unset"
                exit 1
            fi
            if [ -z "${VAR-unset}" ]; then
                echo "VAR is set to the empty string"
                exit 1
            fi
            if [ -n "${VAR}" ]; then
                echo "VAR is set to a non-empty string"
                exit 1
            fi
            if [ -n "${VAR+set}" ]; then
                echo "VAR is set, possibly to the empty string"
                exit 1
            fi
            if [ -n "${VAR-unset}" ]; then
                echo "VAR is either unset or set to a non-empty string"
                exit 1
            fi
      - uses: actions/checkout@v2

      - name: Create Solution
        run: |
          dotnet new sln --name resharper-test
          mkdir myfiles
          cd myfiles
          ls -la

      - name: Run ReSharper
        uses: ./
        with:
          solution-name: resharper-test.sln
          exclude-list: "**\\appsettings.Local.json;**\\NuGet.Config"
          severity-level: WARNING